export const SCREENS = {
  FAVORITE_SCREEN: "FavoriteScreen" as const,
  SETTINGS_NAVIGATOR: "SettingsNavigator" as const,
  MAIN_BOTTOM_NAVIGATOR: "MainBottomNavigator" as const,
  MENU_SCREEN: "MenuScreen" as const,
  SETTINGS_SCREEN: "SettingsScreen" as const,
  ORDER_FAVORITE_SCREEN: "OrderFavoriteScreen" as const,
  ORDER_RESTAURANT_SCREEN: "OrderRestaurantScreen" as const,
  RESTAURANT_SCREEN: "RestaurantScreen" as const,
  REVIEW_MAIN_SCREEN: "ReviewMainScreen" as const,
  REVIEW_LIST_SCREEN: "ReviewListScreen" as const,
  REVIEW_WRITE_SCREEN: "ReviewWriteScreen" as const,
  APP_INFO_SCREEN: "AppInfoScreen" as const,
  ADMIN_ADD_MENU_SCREENS: "AddMenuScreen" as const,
  ADMIN_ADD_CAFE_SCREENS: "AddCafeScreen" as const,
  ADMIN_ADD__SCREENS: "AddReviewScreen" as const,
  CLIENT_CONFIG_SCREEN: "ClientConfigScreen" as const,
};
